### ISSUE TITLE
Hylland - Reporting Tool Comments

### ISSUE THREAD

**Issue by mikehylland** [UGS-GIO/geohaz#33]
- [x] Any possibility of giving the user a heads up right off the bat regarding the maximum allowable extent for the area of interest? I found myself getting the "Area of interest is too large, try a smaller extent" message multiple times as I gradually selected smaller and smaller areas, thinking, "Hmmm, this is kinda lame..." I think that response could be mitigated somewhat by telling the user in the "Report Generator" pop-up window that the custom reports are intended for relatively small areas (maybe provide a guideline for maximum area). In other words, establish the expectation level right at the start.

- [x] Report Summary, table: I see one column with the heading "Mapped Hazard Severity." Per my comments elsewhere regarding the word "severity," I think this is misleading. With the exception of ground shaking, where the map category may include the word "severe," what we're mapping is susceptibility, which is different from severity. Susceptibility refers to the degree to which something may or may not happen; severity refers to how bad or impactful the thing that happens may be. For the column heading, how about "Mapped Hazard Category" (or just "Hazard Category")?

- [x] In the report I generated, the table shows two instances of "Collapsible Soil Susceptibility," both with a Hazard Severity of "Unlikely." Both hyperlinks appear to take me to the same place in the report. Something that needs to be fixed?

- [x] Earthquake Hazard, main paragraph: There are a couple instances where "M" (magnitude) is bold. They should all be plain text (no bold), as we're using "magnitude" generally (i.e., not specifying a particular type of magnitude. The bold M had previously been used to indicate moment magnitude, but that convention seems to have fallen out of use.). (I also see a bold M in "Liquefaction Susceptibility"; the bold should be removed anywhere "M" is used.)

- [x] Earthquake Hazard: In the list of earthquake hazards, is there a formatting issue with "Earthquake-Triggered Landslides and Rockfall"? Only the word "Earthquake" is bold, and the rest of the hazard name is separated from the word "Earthquake."

- [x] In reference lists, I see a reference to the Glen Canyon hazards report as a contract deliverable. This should be updated to reference the Special Study.

- [x] My report produces a section on "Flood Hazard." Under the flood hazard map, two hazard categories are shown, but the map itself doesn't show any mapped hazard areas, either within my area of interest or in the immediate surroundings. This seems to be a problem with the map rendering, as the main app does indeed show two hazard categories in my area of interest.

- [x] One additional comment regarding the main app page: Are we going to provide a version and date of most recent update (similar to what we do on the existing Q Faults app)? Seems like that might be important for tracking and referencing updates. Also, on the custom report, perhaps right below the "Report generated on" line, might be helpful to add a line something to effect of: "Data from Utah Geologic Hazards Portal, version X."

**Comment by JCastleton** [comment]
"Report Summary, table: I see one column with the heading "Mapped Hazard Severity." Per my comments elsewhere regarding the word "severity," I think this is misleading. With the exception of ground shaking, where the map category may include the word "severe," what we're mapping is susceptibility, which is different from severity. Susceptibility refers to the degree to which something may or may not happen; severity refers to how bad or impactful the thing that happens may be. For the column heading, how about "Mapped Hazard Category" (or just "Hazard Category")?"

This has been fixed in the tables and the text and just needs to be updated. 


![image](https://user-images.githubusercontent.com/63422273/81116596-e7be8f80-8ee2-11ea-9566-a2ee862108ed.png)

So the Table 1 description is fixed but I don't know where the table itself is sourced from to change the "Mapped Hazard Severity" there.

**Comment by JCastleton** [comment]
"Earthquake Hazard, main paragraph: There are a couple instances where "M" (magnitude) is bold. They should all be plain text (no bold), as we're using "magnitude" generally (i.e., not specifying a particular type of magnitude. The bold M had previously been used to indicate moment magnitude, but that convention seems to have fallen out of use.). (I also see a bold M in "Liquefaction Susceptibility"; the bold should be removed anywhere "M" is used.)"


FIXED in both text docs and code in tables. Will show up when republished by @marthajensen

**Comment by JCastleton** [comment]
"In reference lists, I see a reference to the Glen Canyon hazards report as a contract deliverable. This should be updated to reference the Special Study."

Working on this

**Comment by marshallrobinson** [comment]
> * Any possibility of giving the user a heads up right off the bat regarding the maximum allowable extent for the area of interest? I found myself getting the "Area of interest is too large, try a smaller extent" message multiple times as I gradually selected smaller and smaller areas, thinking, "Hmmm, this is kinda lame..." I think that response could be mitigated somewhat by telling the user in the "Report Generator" pop-up window that the custom reports are intended for relatively small areas (maybe provide a guideline for maximum area). In other words, establish the expectation level right at the start.

@mikehylland How about the following text: "We recommend zooming in to a neighborhood or closer when using the Report Generator as it is intended for small areas of interest. A notification telling you "Area of interest is too large, try a smaller extent" will appear when you need to zoom in more."

**Comment by mikehylland** [comment]
Might be okay, although maybe not as helpful as it could be if you're
looking at areas on the Wasatch Plateau, Zion NP, Glen Canyon NRA, etc.

Can we say about how many square miles in extent the area of interest is
limited to?

Something like: "The Report Generator is designed to provide a summary of
information for relatively small areas (about X square miles). If your area
of interest is larger than that, you will see a notification prompting you
to select a smaller area."


Michael D. Hylland, PG
Deputy Director
Geologic Information and Outreach Program Manager
Utah Geological Survey
P.O. Box 146100
1594 W. North Temple, Ste. 3110
Salt Lake City, Utah 84114-6100

801-537-3382
mikehylland@utah.gov
geology.utah.gov

**Comment by JCastleton** [comment]
In the report I generated, the table shows two instances of "Collapsible Soil Susceptibility," both with a Hazard Severity of "Unlikely." Both hyperlinks appear to take me to the same place in the report. Something that needs to be fixed?

None of the "Susceptibility" categories should be named unlikely. It looks like the middle two units have been named unlikely in this table. The mapped units are not unlikely, just less than the others. Complicated descriptions there. 

they should be named
High
Collapsible Soil 1
Collapsible Soil 2
Collapsible Soil 3
Collapsible Soil 4

Because the unit symbols are not being shown on the maps I will add those terms to the description. Who can change those terms in the table? @jjhi11

**Comment by marthajensen** [comment]
> In the report I generated, the table shows two instances of "Collapsible Soil Susceptibility," both with a Hazard Severity of "Unlikely." Both hyperlinks appear to take me to the same place in the report. Something that needs to be fixed?
> 
> None of the "Susceptibility" categories should be named unlikely. It looks like the middle two units have been named unlikely in this table. The mapped units are not unlikely, just less than the others. Complicated descriptions there.
> 
> they should be named
> High
> Collapsible Soil 1
> Collapsible Soil 2
> Collapsible Soil 3
> Collapsible Soil 4
> 
> Because the unit symbols are not being shown on the maps I will add those terms to the description. Who can change those terms in the table? @jjhi11

These descriptions need to be changed in the HazardUnitTextTable (report table) under the UnitName column 
![image](https://user-images.githubusercontent.com/11522897/81225394-63cddb80-8fa6-11ea-88fd-123f40fbebd0.png)

**Comment by JCastleton** [comment]
> Collapsible Soil 1


FIXED
Edited the unit description to add words describing SU1css, SU2css etc as collapsible soil 1, 2, etc. Fixed both the Unit_Descriptions table and the HazardUnitTextTable as well as both word docs.

**Comment by JCastleton** [comment]
Done in tables and text docs. 

Earthquake Hazard, main paragraph: There are a couple instances where "M" (magnitude) is bold. They should all be plain text (no bold), as we're using "magnitude" generally (i.e., not specifying a particular type of magnitude. The bold M had previously been used to indicate moment magnitude, but that convention seems to have fallen out of use.). (I also see a bold M in "Liquefaction Susceptibility"; the bold should be removed anywhere "M" is used.)

Will need review when republished to see if any missed.

**Comment by JCastleton** [comment]
DONE - added the DOI as well. Will be republished when @marthajensen is done with html in the table

in reference lists, I see a reference to the Glen Canyon hazards report as a contract deliverable. This should be updated to reference the Special Study.

**Comment by marthajensen** [comment]
The report tables were re-published. I check-marked the boxes of the comments that were fixed with the latest publishing.
