### ISSUE TITLE
Add Southern UT Fault Mapping data to hazards portal

### ISSUE THREAD

**Issue by AHiscock** [UGS-GIO/geohaz#75]
Myself and Tyler K. have finished up our new southern UT fault mapping. Here is a list of the faultnums that need to be copied into the Hazards Portal within our study area boundary (located here - M:\Shared drives\UGS_Shared\Hazards\Fault Mapping\SUFM_Project Extent\SUFM_ProjectExtent.shp)

Data is on UGHP SDE in this feature class: UGHP.UGHPADMIN.QFault_SUFM 
FaultNums:
997a
997b
998a
998b
998c
1004b
2520
2522
2524
2527
2528
2529
2532
2533
2534
2535
2536
2537
2550
2558

I don't have the special-study zones associated with these faults quite ready yet (they are being reviewed by Steve, hopefully he'll have them done today or tomorrow, and then I can provide that data as well).

This is my first time startting a GitHub issue, so I hope I provided everything you need! Let me know if I missed anything. I will be on A/L starting this Wednesday (9/29) through 10/11, with some limited email access/checking going on.

**Comment by marthajensen** [comment]
@AHiscock 

Just a few questions -- 

Has the SUFM data already been through the Hazards review process (including topology)? Is there a report reference for the data that needs to be included in the Hazards portal?

I doubt I'll get to this before you leave. Would Emily be the best person to ask questions to as they arise? Will she be the person who reviews the data before publishing it to the web?

**Comment by AHiscock** [comment]
@marthajensen 

Yes, it has been through the Hazards review process. I ran topology on it last week, since we no longer have a Gordon. I haven't run topology in a long time, but I'm 99% sure I did it right. 
I set up a report reference link in GeoData, like we did for our last fault mapping project. Just a note - the link is set to private currently, and won't be "live" with the final report until we get it completed and through review. We've told the USGS we would have the FTR report submitted to them by the end of October. 
Here's the reference report link - https://geodata.geology.utah.gov/pages/view.php?ref=65953

No worries about getting to this before I leave. I just spoke with Emily, and she's ok with being the person for questions and such while I am gone. 

Thanks Martha.

**Comment by AHiscock** [comment]
@marthajensen 

OK - I have finished the special study zones that go with this fault mapping. They are all in a shapefile located here **M:\Shared drives\UGS_Shared\Hazards\Fault Mapping\SUFM_SpecialStudyZones\SUFM_SSZ_Master.shp**

Everything should be ready to go from me. As I mentioned, @emkleb should be available for any questions that may come up while I am gone. 

Thanks Martha and Emily!

**Comment by marthajensen** [comment]
@emkleb The data is ready for review. Please review the following pieces of data:

**Hazards Portal:** 

_Study Areas_
"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\Geologic_Hazards_Geodatabase_Review_Version.gdb\Study_Areas

- I wasn't sure what to put in the "Name" field for the new data in the attribute table. Please have a look and tell me what to add or add something. It needs to match the name in the MappedHazardsTable (below). I also added the report reference above (https://geodata.geology.utah.gov/pages/view.php?ref=65953) to the Repor_ID and URL1 fields. However, @AHiscock indicated the report was set to Private in GeoData. When I click on the link, it appears the report is viewable.

_Quaternary Faults_
"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\Geologic_Hazards_Geodatabase_Review_Version.gdb\Quaternary_Faults

-Check the new fault data 

_Special Study Zone_
"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\Geologic_Hazards_Geodatabase_Review_Version.gdb\Surface_Fault_Rupture_Hazard_Special_Study_Zone

-Check the new special study zones and the mapped scale. I think this data was mapped at 1:10,000 so I added that information

**Reporting tool data**

"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Final_Report_Tables\HazardUnitTextTable.csv"

 - the only thing that changed in the HazardUnitTextTable is the quaternary fault data at the end of the table

"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Final_Report_Tables\MappedHazardsTable.csv"

-Please check the name of the study in Row 117 and 118. The name in these rows needs to match the name in the Study_Areas feature class. 


**UGRC data:**
This is the undissolved version of the feature class that we provide to the UGRC
"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Master_QfaultsData\Qfaults_AGRC.gdb\Qfaults



Once you give me the go-ahead, I will move the data to the LIVE version of our geodatabase.

**Comment by emkleb** [comment]
I apologize for my slightly delayed review. I didn't see the Github email, and I only checked on it today.

Hazards Portal:
_Study Areas_
"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\Geologic_Hazards_Geodatabase_Review_Version.gdb\Study_Areas
- Adam put a temporary file for the URL, so it works, but the final report isn't up yet. 
- I added the name "Sevier and Hurricane faults" to the  GDB above and the CSV

"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\Geologic_Hazards_Geodatabase_Review_Version.gdb\Quaternary_Faults
- One thing I noticed, and this may be a  legacy database thing, but in the non-domain fields (ie. fault_name), some field are <Null> while others are blank (no spaces). Why is that? I only ask because Arc sees a blank value not as <Null>, but as something else, even though it should technically be <Null>.
- Looks like, spatially, all of the fault data are there.
- Attributes look good for each fault number

_Special Study Zone_
"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\Geologic_Hazards_Geodatabase_Review_Version.gdb\Surface_Fault_Rupture_Hazard_Special_Study_Zone
- It looks like the wrong data was added for this layer. It should be the "SUFM_SSZ_Master.shp" Adam listed. It's a polygon shapefile that very closely follows the fault mapping. Please take another look.
- 1:10k is correct. Thanks for updating.

This is the undissolved version of the feature class that we provide to the UGRC
"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Master_QfaultsData\Qfaults_AGRC.gdb\Qfaults
- Looks good.

**Comment by AHiscock** [comment]
@marthajensen 

Done making changes. Here's a summary of what I've done:

Study Areas
"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\Geologic_Hazards_Geodatabase_Review_Version.gdb\Study_Areas

- All fixed. Trimmed the polygon for the "Sevier and Hurricane" fault mapping study area. One quick note - can we change the "Name" field to **Washington/Hurricane/Sevier-Toroweap Fault Zones** in the Study_Areas feature class? 
- New polygons for both the WFZ and Bear Lake/Oquirrh projects are in the feature class

Special Study Zone
"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\Geologic_Hazards_Geodatabase_Review_Version.gdb\Surface_Fault_Rupture_Hazard_Special_Study_Zone

- Everything should be good to go here. I'll do another quick review once you re-do the lines. 

I think thats it! Let me know when you are done and ready for me to review again. Thanks!

**Comment by marthajensen** [comment]
@AHiscock 

I've rewrote parts of the workflow script and ran it again to encompass the study area issue that we ran into. 

Please check the following datasets:

**Hazards Portal**

Study Areas

"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\Geologic_Hazards_Geodatabase_Review_Version.gdb\Study_Areas

- "Name" field changed to Washington/Hurricane/Sevier-Toroweap Fault Zone

Quaternary Faults

"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\Geologic_Hazards_Geodatabase_Review_Version.gdb\Quaternary_Faults

- Last dataset had 1599 faults - new dataset has 1690 faults

**Reporting tool data**

"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Final_Report_Tables\HazardUnitTextTable.csv"

- the only thing that changed in the HazardUnitTextTable is the quaternary fault data at the end of the table

"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Final_Report_Tables\MappedHazardsTable.csv"

- "Sevier and Hurricane faults" changed to  "Washington/Hurricane/Sevier-Toroweap Fault Zone" (last 2 rows of the CSV)

**Quaternary Faults for UGRC**

"G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Master_QfaultsData\Qfaults_AGRC.gdb"

- Last dataset had 7865 faults - new dataset has 13298. One potential issue, which can't be solved easily (or maybe at all) by code, is the Summary field. For fault 1004b the Summary field has information outside the new study area, but not within it. I'm sure this same thing occurs across the Study Area in multiple places (I only checked one location).  If this is problematic, we will need to edit the attribute table in GIS. This is also the case with the Hazards Portal faults.

**Comment by emkleb** [comment]
The Summary field is not necessary to push outside of UGS. It is a legacy
field used by USGS, but it's not maintained by them anymore. It might not
hurt to keep it, because it contains a lot of good geologic information in
addition to the other attributes.

option 1- keep the field, and just have some parts of the same fault number
have a summary, and some without (ex. 1004b). Might be a little sloppy, but
it preserves the information. This information can also be found on the
USGS archived report pages (example for 1004b
<https://earthquake.usgs.gov/cfusion/qfault/show_report_AB_archive.cfm?fault_id=1004&section_id=b>
).
option 2- remove the field completely from the UGRC delivery.

I'm in favor of option 2, since we do have the URL for the USGS webpage,
where users will be able to find the summary information that is in the
summary field.

**Comment by AHiscock** [comment]
@emkleb - Thanks for the response. I think option 2 sounds good. One question - Our new data has nothing in the USGS_Link URL field, I'm guessing we need to get that added?

@marthajensen is out until Monday, so we can just resolve this then.

**Comment by marthajensen** [comment]
@AHiscock @emkleb 

@AHiscock I changed around the qfault symbology this morning to thinner lines when zoomed in. Have a look and let me know

@emkleb  Let's take care of adding the new data to the SDE during our meeting on Wednesday.

**Comment by AHiscock** [comment]
@marthajensen That looks MUCH better. Thanks. 
![image](https://user-images.githubusercontent.com/90356526/139873470-b4e97a67-3a53-4236-a880-91ccd4de8eee.png)
